# Generated by Django 3.1.7 on 2021-10-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('affiliateName', models.CharField(max_length=40)),
                ('number', models.IntegerField()),
                ('profile', models.URLField()),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_discription', models.CharField(max_length=200)),
                ('date_valid_till', models.DateField()),
                ('status', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_limit', models.CharField(choices=[('one-day', 'one-day'), ('three-day', 'three-day'), ('one_week', 'one_week'), ('one_month', 'one_month'), ('forever', 'forever')], max_length=40)),
                ('photo_offer', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubAffiliate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_affiliates', models.BooleanField()),
                ('change_offers', models.BooleanField()),
                ('see_reports', models.BooleanField()),
                ('scan_members', models.BooleanField()),
                ('get_notifications', models.BooleanField()),
                ('affiliate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliate')),
            ],
        ),
    ]
