# Generated by Django 3.1.7 on 2021-10-24 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('member', '0001_initial'),
        ('ambassador', '0001_initial'),
        ('affiliate', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subaffiliate',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.member'),
        ),
        migrations.AddField(
            model_name='offer',
            name='affiliate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='affiliate.affiliate'),
        ),
        migrations.AddField(
            model_name='affiliate',
            name='membership',
            field=models.ManyToManyField(blank=True, related_name='affiliates', to='ambassador.Membership'),
        ),
    ]
